project:
  type: website
  output-dir: docs

website:
  title: "PER-HE Publications"
  description: "Publications by the UK & Ireland Physics Higher Education Research community"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: All Publications
      - href: authors.qmd
        text: Authors
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/nicolaslab/per-he-publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
